trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'fashionwebprodacr.azurecr.io/laravel-ecommerce-web'
  phpVersion: 8.3.7

steps:
- task: UsePHP@0
  inputs:
    version: '$(phpVersion)'

- script: |
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php composer-setup.php
    php -r "unlink('composer-setup.php');"
  displayName: 'Install Composer'

- script: |
    php composer.phar install
  displayName: 'Install Dependencies'

- script: |
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache
  displayName: 'Run Artisan Commands'

- task: Docker@2
  inputs:
    containerRegistry: 'azure-devops-acr'
    repository: $(imageName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'drop'
    publishLocation: 'PipelineArtifact'
