version: '3.4'
services:

  #PHP Service
  app:
    image: laravel/fashion-shop
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=DB_IS207
      - DB_USERNAME=root
      - DB_PASSWORD=root

  #Nginx Service
  webserver:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  #MySQL Service
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: DB_IS207
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql

  #Adminer Service
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080