apiVersion : apps/v1
kind: Deployment
metadata:
  name: fashionecommercewebsite 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fashionecommercewebsite
  template:
    metadata:
      labels:
        app: fashionecommercewebsite 
    spec:
      containers:
        - name: fashionecommercewebsite 
          image: fashionwebprodacr.azurecr.io/fashionecommercewebsite
          ports:
          - containerPort: 80